### ISSUE TITLE
Duplicate episode dialogue

### ISSUE THREAD

**Issue by gkaramanis** [filmicaesthetic/stringr-things#3]
Thanks for the dataset!

I spotted two pairs of episodes with the same dialogue: S02E09 - S04E09 and S03E08 - S04E08

**Comment by filmicaesthetic** [comment]
Hey Georgios,

Thanks so much for pointing this out - I've just updated the script and dataset. I'll try to let the TidyTuesday team know too.

Thanks!

**Comment by gkaramanis** [comment]
Great!
